### ISSUE TITLE
Suggest rename CocoaAsyncSocket.framework.

### ISSUE THREAD

**Issue by youngshook** [github-xiaogang/woodpeckeriOS#1]
WoodPeckeriOS.framework contain CocoaAsyncSocket.framework. App  will have warning log when already contain CocoaAsyncSocket.framework .
Suggest rename CocoaAsyncSocket.framework.

**Comment by github-xiaogang** [comment]
okay, I'll check it.

**Comment by github-xiaogang** [comment]
I'have check that ,and consider the copyright problem, and make the framework easy to use, I decide to just ignore this.
