### ISSUE TITLE
Non-public API usage - UNLegacyNotificationTrigger

### ISSUE THREAD

**Issue by gaurav02712** [github-xiaogang/woodpeckeriOS#10]
Our app got rejected from apple with below messages - 

```
**Non-public API usage**:

The app contains or inherits from non-public classes in Frameworks/WoodPeckeriOS.framework/WoodPeckeriOS: UNLegacyNotificationTrigger
```

> If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed

**Comment by github-xiaogang** [comment]
@GauravT9l oh, no! the framework should never be used in the production mode, that will cause safety problem.

**Comment by gaurav02712** [comment]
So before making a production build, I have to manually remove this framework and have to reinstall for debugging purpose?
Any better alternative options as I really would like to use this.

**Comment by github-xiaogang** [comment]
Hi, if you use pod,  `pod 'WoodPeckeriOS', :configurations => ['Debug']`
If you added framework manually, I'll provide a better method in the near future, I'll tell you when it's okay.

**Comment by gaurav02712** [comment]
We are using Pod only, so suggested one should work for of most the people I guess, Thanks
