### ISSUE TITLE
networking 的 request 問題

### ISSUE THREAD

**Issue by SuYungCheng** [github-xiaogang/woodpeckeriOS#11]
您好，
想请问networking的功能下，
目前只能看到GET时的request body，
如何能看到POST的request body及参数呢？
谢谢！

**Comment by github-xiaogang** [comment]
@SuYungCheng 你好，谢谢反馈
1. Post参数目前仅支持查看Content-Type为application/x-www-form-urlencoded类型
2. Post request body现在还不支持，后面会尽快完善

**Comment by Arc-lin** [comment]
现在依然不支持吗，我使用的是1.2.9 版本
