### ISSUE TITLE
手动导入怎样让release模式不适用本库

### ISSUE THREAD

**Issue by weixianlove** [github-xiaogang/woodpeckeriOS#12]
手动导入怎样让release模式不适用本库，手动导入不希望在release模式下使用，怎样设置么

**Comment by github-xiaogang** [comment]
@weixianlove 你好，会尽快整理文档，完成后通知您

**Comment by github-xiaogang** [comment]
@weixianlove 你好，请参考文档进行设置即可http://www.woodpeck.cn/cnmanuallink
有问题再联系
