### ISSUE TITLE
有一些小BUG 希望解决一下

### ISSUE THREAD

**Issue by josercc** [github-xiaogang/woodpeckeriOS#13]
我们组很多同事都在同一个局域网下面，模拟器状态。比如我新建一个 Demo，不设置参数。我就可以读取同事的工程 同事无法读取

**Comment by github-xiaogang** [comment]
你好
1. 请确认下WoodPeckeriOS.framework版本是否为最新版1.2.1，如果不是请先更新后，再试一下
2. 如果不是上面问题请加一下QQ 2767577447，或 [Slack群](https://join.slack.com/t/woodpeckerapp/shared_invite/enQtNjMzMTY3MDczMDA4LTM4NTQ5OGRjMTIxZWMxMDdmZmVlNjQ4NjRhZmQ3YTE0NzFkMDBmNGE5NmE2MzRjMjYzZjk2Yzk5OGNjNDUwMTM) 方便讨论
