### ISSUE TITLE
Xcode 11 GM

### ISSUE THREAD

**Issue by weixianlove** [github-xiaogang/woodpeckeriOS#15]
dyld: Library not loaded: @rpath/WoodPeckeriOS.framework/WoodPeckeriOS
  Referenced from: /var/containers/Bundle/Application/63B488E4-AF72-4A9C-9A4F-913A44A386AB/myapp.app/myapp
  Reason: image not found
(lldb)

**Comment by github-xiaogang** [comment]
@weixianlove 请试下将framework添加到Embeded Binaries位置，可参考这个链接里面有介绍 http://www.woodpeck.cn/cnusage.html

如果还有问题，请继续联系

**Comment by weixianlove** [comment]
习惯性在general 添加。。。结果 11在general没有了。。。尴尬,已经解决，非常感谢
