### ISSUE TITLE
WoodPeckeriOS.framework里mock.js中的printLog在某些情况会导致web页白屏

### ISSUE THREAD

**Issue by xtyHY** [github-xiaogang/woodpeckeriOS#17]
在web页中js执行`console.log()`的时候，若入参中有`undefined`的时候会报错导致后续js代码无法继续执行。建议增加`value == undefined`的判断。

![image](https://user-images.githubusercontent.com/15955583/71717126-00923800-2e52-11ea-8035-3e2e6cef8a4f.png)

另外，发现在使用safari调试时，无论console.log()啥都是undefined，且在mac版的woowoodpecker里也没有看到任何相关日志信息。
![image](https://user-images.githubusercontent.com/15955583/71717366-d1c89180-2e52-11ea-8c2c-c49ba04d3253.png)

**Comment by github-xiaogang** [comment]
@xtyHY 谢谢，反馈收到，下个版本会修复下。

**Comment by github-xiaogang** [comment]
@xtyHY 已做优化，请将app和framework升级到1.2.5
