### ISSUE TITLE
在XCode11 ios13 下wkwebview分享图片引起的崩溃

### ISSUE THREAD

**Issue by ljh740** [github-xiaogang/woodpeckeriOS#18]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to add script message handler with name 'wkwebviewjsHandler' when one already exists.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   WebKit                              0x00007fff2d0b20a1 -[WKUserContentController addScriptMessageHandler:name:] + 209
	4   WoodPeckeriOS                       0x00000001074ed6c8 -[ADHWebDebugService doWKWebViewConsoleMock:] + 376
	5   WoodPeckeriOS                       0x00000001074ecdc3 -[ADHWebDebugService wkwebviewInit:] + 163
	6   WoodPeckeriOS                       0x00000001074ecc5e -[ADHWebDebugService wkwebview:initWithFrame:configuration:] + 94
	7   WoodPeckeriOS                       0x00000001074ec7a4 __58+[ADHWebDebugService injectWKWebViewInitWithConfiguration]_block_invoke_2 + 260
	8   LinkPresentation                    0x00007fff27429440 -[LPURLFetcher fetchWithConfiguration:completionHandler:] + 454
	9   LinkPresentation                    0x00007fff2742ab9d -[LPFetcherGroup startFetchesIfNeeded] + 442
	10  LinkPresentation                    0x00007fff2742a79e -[LPFetcherGroup _addFetcher:atIndex:] + 238
	11  LinkPresentation                    0x00007fff2742a81e -[LPFetcherGroup appendFetcher:] + 75
	12  LinkPresentation                    0x00007fff27454e40 -[LPMetadataProvider _fetchImplicitIcons] + 914
	13  LinkPresentation                    0x00007fff27452415 -[LPMetadataProvider startFetchingMetadataForURL:completionHandler:] + 349
	14  LinkPresentation                    0x00007fff274527e6 -[LPMetadataProvider _startFetchingMetadataForURL:completionHandler:] + 257
	15  LinkPresentation                    0x00007fff2747d572 -[LPLinkView _fetchMetadataForURL:completionHandler:] + 306
	16  LinkPresentation                    0x00007fff2747d84e -[LPLinkView _fetchMetadata] + 170
	17  LinkPresentation                    0x00007fff2747ccbe -[LPLinkView initWithMetadataLoadedFromURL:] + 43
	18  ShareSheet                          0x00007fff43ae2cae -[UIActivityContentViewController configureHeaderViewIfNeeded] + 717
	19  ShareSheet                          0x00007fff43ae9626 -[UIActivityContentViewController setPhotosCarouselViewController:] + 66
	20  ShareSheet                          0x00007fff43aee5dc -[UIActivityViewController configureContentViewIfNeeded] + 1151
	21  ShareSheet                          0x00007fff43af5301 -[UIActivityViewController viewDidLoad] + 66

**Comment by ljh740** [comment]
![image](https://user-images.githubusercontent.com/9330229/72659701-f00bc100-39fe-11ea-9f40-06547e0fe965.png)

**Comment by github-xiaogang** [comment]
谢谢，收到反馈啦，下个版本会修复掉。

**Comment by NicolasKim** [comment]
这个问题已经修复了吗？ 我这里也出现了

**Comment by github-xiaogang** [comment]
@NicolasKim 抱歉，还没有修复，下个版本会修复掉

**Comment by github-xiaogang** [comment]
@ljh740 @NicolasKim 问题修复了，请将app和framework升级到1.2.5
