### ISSUE TITLE
有没有类似 reveal 使用 xcode 断点调用的方式

### ISSUE THREAD

**Issue by iOSleep** [github-xiaogang/woodpeckeriOS#21]

**Comment by iOSleep** [comment]
用类似reveal的方式可以加载 （同样只支持模拟器），需要下载 ios 的 framework

![QQ20201015-164526](https://user-images.githubusercontent.com/26478957/96099618-056a3900-0f06-11eb-9f45-cb6ecd4422d7.png)

```
expr (Class)NSClassFromString(@"ADHOrganizer") == nil ? (void *)dlopen("/Users/maxu/Desktop/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS", 0x2) : ((void*)0)
```

我 framework 放在了我的桌面 注意要绝对路径 

![image](https://user-images.githubusercontent.com/26478957/96100699-3eef7400-0f07-11eb-879f-3a2d14e2c563.png)

将断点移到user下，本机就可以不用填多个了

**Comment by github-xiaogang** [comment]
@iOSleep cool!
