### ISSUE TITLE
ios14 network

### ISSUE THREAD

**Issue by bk97531** [github-xiaogang/woodpeckeriOS#22]
你好，ios14的network里监听不到app的网络请求了，需要修改什么配置吗？
 Local Network Usage Description和Bonjour services已经加了

**Comment by github-xiaogang** [comment]
你好，iOS14网络抓包问题修复了，暂时请到下面链接下载最新的framework替换项目里的(手动导入/pod安装)WoodpeckeriOS.framework文件即可
http://www.woodpeck.cn/assets/framework/WoodPeckeriOS.framework.zip

**Comment by bk97531** [comment]
好的，谢谢
