### ISSUE TITLE
Xcode12无法正常抓取网络请求 其他功能正常

### ISSUE THREAD

**Issue by jhchenchong** [github-xiaogang/woodpeckeriOS#23]
WoodPeckeriOS 1.2.8  Xcode12.0  
模拟器跟真机都无法抓取网络请求  
控制台也正常输出了[🌿Woodpecker]: service "adh.network" created

**Comment by github-xiaogang** [comment]
你好，参考 #22

**Comment by jhchenchong** [comment]
谢谢！
