### ISSUE TITLE
双指长按不显示 woodpecker 菜单

### ISSUE THREAD

**Issue by iTofu** [github-xiaogang/woodpeckeriOS#25]
项目在 iOS 13+ 使用了SceneDelegate 代替 AppDelegate，不知道是否与这个有关？

**Comment by github-xiaogang** [comment]
晚点确认后回复您

**Comment by iTofu** [comment]
好的，麻烦了

**Comment by github-xiaogang** [comment]
确认是iOS13的sceneDelegate问题，是没有设置windowScene展示自定义window失效了。
后台连接和其他功能是正常的，UI展示有问题，下个版本会做下兼容，谢谢反馈！

**Comment by iTofu** [comment]
好的👍
下版本发布了 close 吧，我顺带收到通知~
