### ISSUE TITLE
Not work for big sur

### ISSUE THREAD

**Issue by jahov0820** [github-xiaogang/woodpeckeriOS#26]
After upgrade to Big Sur, waiting connect always

**Comment by github-xiaogang** [comment]
你好，应该是iOS14新增本地网络权限的原因，按照下面的方法试一下（可以在http://www.woodpeck.cn/cnusage看到）

iOS 14系统增加了本地网络访问权限开关，请确认您App拥有此权限，如果您使用最新的Xcode 12+构建，请在Info.plist增加下面两项

在`Privacy - Local Network Usage Description`添加本地网络使用描述
在`Bonjour services`列表添加 `_adhp._tcp`
