### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by Kaspik** [github-xiaogang/woodpeckeriOS#27]
Hey!

We are currently trying to switch everything from CocoaPods to SPM - Woodpecker seems to not have SPM support.
Are you thinking about adding it?

Thanks!

**Comment by github-xiaogang** [comment]
Hi !

I'll check it later, this app was using objective-c, so it may takes some time to support SPM.
Currently you could add the framework to your project, it should works for swift project. (Don't forget to remove it when build for AppStore)

**Comment by Kaspik** [comment]
The reason I'm saying this is that we are using M1 devices already, so we need the framework to be universal framework (for arm64 and arm64 simulators too). Is the framework itself already updated?

**Comment by github-xiaogang** [comment]
Okay, I got it.
It has not support  M1 arch yet, I will update it as soon as I could (I don't have M1 device, will ask friends to test it  😂 )

**Comment by Kaspik** [comment]
Thanks, if you create PR / branch with update, I can test it too! :)

**Comment by Kaspik** [comment]
Happy Friday @github-xiaogang - any update here? Something I can test for ya? :)

**Comment by github-xiaogang** [comment]
@Kaspik sorry for the late reply. I had read some docs, and it should be quite easy to support SPM and M1 arch, Please wait about 2 days, I'll tell you when it's done.

**Comment by Kaspik** [comment]
Awesome, thanks!

**Comment by github-xiaogang** [comment]
@Kaspik  SPM should be okay now. please add  https://github.com/appwoodpecker/woodpecker-ios.git

**Comment by Kaspik** [comment]
Thanks, will try in about hour! 🎉

**Comment by Kaspik** [comment]
Works!

The only problem now is that SPM doesn't have conditional linking - so for Cocoapods, you can actually do `pod 'WoodPeckeriOS', :configurations => ['Debug']` and it will link only in Debug config, but in SPM, there is no such a thing and it would mean that adding Woodpecker via SPM results in framework being added in production for release.

We will need to come up with some solution for this... 😭
