### ISSUE TITLE
ARM64 XCode: Missing arm64 architecture for simulators

### ISSUE THREAD

**Issue by Kaspik** [github-xiaogang/woodpeckeriOS#28]
Hey again here!

Because of the issue mentioned in my previous issue about SPM, we are forced to stay with CocoaPods for now. There is a problem with building our project on M1 devices because the vendored framework is not sully universal framework.

Related issue on Realm: https://github.com/realm/realm-cocoa/issues/6968 - I believe it was resolved the same way as it could be here (https://github.com/realm/realm-cocoa/pull/6982/files)

Current framework is built for these:
```
 ~  file Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS 
Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS: Mach-O universal binary with 4 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [i386] [x86_64] [arm64]
Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS (for architecture i386):	Mach-O dynamically linked shared library i386
Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

When trying to build our project for Simulator on ARM M1 mac, it results in error: `Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/kaspik/Documents/Vyvoj/ClassDojo/dojo-behavior-ios/Pods/WoodPeckeriOS/WoodPeckeriOS.framework/WoodPeckeriOS' for architecture arm64`

I believe there is multiple issues, one of them is podspec that `excludes` arm64:
https://github.com/appwoodpecker/woodpecker-ios/blob/1785dcc41649dc4eae96fb9386aff19e33dac920/WoodPeckeriOS.podspec#L13

Not sure if that's enough. Let me know if you need more info for the universal lib. :)

**Comment by github-xiaogang** [comment]
Thanks for these information.

1. Yes, SPM seems has not support conditional link [Package Manager Conditional Target Dependencies](https://github.com/apple/swift-evolution/blob/main/proposals/0273-swiftpm-conditional-target-dependencies.md)

Let's wait apple.

2. So, that means everything will be okay  if we rebuild the framework with simulator arm64 included?
I'll try it later.

**Comment by Kaspik** [comment]
2) Hopefully, excluding the arch shouldn't be necessary anymore. :)

Thanks!

**Comment by github-xiaogang** [comment]
Hi, I had updated pod repo 1.2.92 with simulator am64 included, using the official XCFramework format, you could try it.
The SPM package was also updated to 1.2.92.

But I didn't remove this in podspec file
` s.user_target_xcconfig        = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' } 
`
there're two reasons:

1. I'm not using M1 device, pod lib lint didn't pass without this code. ( pod version, 1.10.1,   Xcode version 12.3)
2. I think those who are not using M1 device still need this code to make everything work.

So, I'm not sure if it will work for you, may be I should build an extra pod for M1 user?

**Comment by Kaspik** [comment]
Hello, thank you for all this! Unfortunately, we had a call yesterday and decided to do a different approach without CocoaPods and create a new target where Woodpecker will be included via SPM and used only for testing and debug purposes, so I'm switching us to SPM anyways. I'll report here if it works as expected on both Intel and M1 processors. :)

**Comment by clindsay3** [comment]
I just ran into this too. The line
`s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' } `
breaks people who are trying to build their app on a simulator on an M1 Mac. 

It was also **really** hard to track down, because it causes the app to try to build with x86_64, which then runs into issues when it tries to import other pods that have (correctly) been built for arm64. So it makes it look like the issue is with a different pod.

Are you sure this line is still needed?

**Comment by clindsay3** [comment]
For what it's worth, I had another pod that looks like they added this line for a while, and then removed it:

https://github.com/krzyzanowskim/OpenSSL/commit/0c82e05a8289d22b5f4a6dd2974be2bb6ace54bc#diff-a1e62b291ff037fc1d2e414f3f28526642fef99e0259323c7bd7d0c76cfe2078

**Comment by github-xiaogang** [comment]
@chrisvasselli Sorry for the late response, I'll check it again.

**Comment by SunShineLOL** [comment]
> 你好，我更新了pod repo 1.2.92，包括模拟器am64，使用官方的XCFramework格式，你可以试试。SPM 包也更新到了1.2.92。
> 
> 但是我没有在 podspec 文件中删除它， `s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' } ` 原因有两个：
> 
> 1. 我没有使用 M1 设备，如果没有此代码，pod lib lint 就无法通过。（pod 版本，1.10.1，Xcode 版本 12.3）
> 2. 我认为那些不使用 M1 设备的人仍然需要此代码才能使一切正常运行。
> 
> 所以，我不确定它是否适合您，也许我应该为 M1 用户构建一个额外的 pod？

Perhaps you can skip the validation: `pod lib lint --skip-import-validation`
