### ISSUE TITLE
无法使用 连不上mac 放弃了

### ISSUE THREAD

**Issue by detecyang** [github-xiaogang/woodpeckeriOS#3]

**Comment by github-xiaogang** [comment]
你好，请检查：
1. 确认app和mac在同一wifi下；
2.检查本地的WoodPeckeriOS.framework 是否与mac版本一致，（framework包内有info.plist文件，里面有版本号），如果版本不对，请使用pod update，将本地仓库更新后再尝试。

如果还有问题，请邮箱联系：woodpeckerapp@163.com

**Comment by detecyang** [comment]
ok

**Comment by github-xiaogang** [comment]
嗯好的，如果还有问题请邮箱联系。问题我先关闭了。
