### ISSUE TITLE
Logger能不能支持swift呢

### ISSUE THREAD

**Issue by bugaio** [github-xiaogang/woodpeckeriOS#30]
Logger能不能支持swift呢?
使用的是 pod 'CocoaLumberjack/Swift' 这个 log的库

**Comment by github-xiaogang** [comment]
swift的log机制和oc有区别，不太容易简单实现。
不过库里面有提供ADHLogger类，你可以在自己的logger方法调用它们实现同步到woodpecker
https://github.com/appwoodpecker/woodpecker-ios/blob/master/WoodPeckeriOS.framework/Headers/ADHLogger.h

**Comment by bugaio** [comment]
好的,  多谢,   我尝试一下。

这么优秀的工具,   真的 再次向您 表示 感谢。
