### ISSUE TITLE
Not getting response (Json view and Json body) when i am trying with on iphone 13 (IOS 15).

### ISSUE THREAD

**Issue by gaurav02712** [github-xiaogang/woodpeckeriOS#31]
Hello, 
I am not able to get the response (JSON text and JSON body) view when I am trying with on iPhone 13 (IOS 15) but this working file when I swift to any IOS 13 simulator.

In attaching screenshot iPhone 13 is on IOS 15 and iPhone 8 is on IOS 13.

<img width="798" alt="Screenshot 2021-10-01 at 1 03 45 PM" src="https://user-images.githubusercontent.com/9942485/135582734-c5a25d77-b4a1-4d04-a5ad-889746e9e620.png">
<img width="803" alt="Screenshot 2021-10-01 at 1 05 45 PM" src="https://user-images.githubusercontent.com/9942485/135582942-90050c13-d204-4157-a73e-2061151227b3.png">

.

**Comment by iTofu** [comment]
+1, with iOS 15, still not working now.

**Comment by iTofu** [comment]
@github-xiaogang

**Comment by gaurav02712** [comment]
> @github-xiaogang

Didn't get it, what you wanna say.

**Comment by github-xiaogang** [comment]
@gaurav02712 @iTofu 

Sorry for the problem, I had tried last weekend, but unfortunately some code sign problem appeared when  on iOS 15 device, but it works fine with iOS 15 simulator in my app.

 I'll try again in this weekend and tell you guy what I find :)

**Comment by iTofu** [comment]
> > @github-xiaogang
> 
> Didn't get it, what you wanna say.

calling the author 😂

**Comment by iTofu** [comment]
> @gaurav02712 @iTofu
> 
> Sorry for the problem, I had tried last weekend, but unfortunately some code sign problem appeared when on iOS 15 device, but it works fine with iOS 15 simulator in my app.
> 
> I'll try again in this weekend and tell you guy what I find :)

env: 
- iOS 15
- iPhone 13 Pro & simulator
- macOS Monterey (12.0.1)

We will wait for the your good news~

**Comment by github-xiaogang** [comment]
Hey! @gaurav02712 @iTofu 
Sorry for the lately response,  I had some good news for you guys!
I found network hook didn't work well under iOS 15 for some reason, and if we move the hook operation before any network request, it works well again, so here's temporary solution:
Put the network hook code before any code in the applicationDidFinishLaunch method
```
- (void)setupNetworkMonitor {
#if DEBUG
    Class clazz = NSClassFromString(@"ADHNetworkObserver");
    if (clazz) {
        SEL selector1 = NSSelectorFromString(@"sharedObserver");
        id network = [clazz performSelector:selector1];
        SEL selector2 = NSSelectorFromString(@"start");
        [network performSelector:selector2];
    }
#endif
}
```

![image](https://user-images.githubusercontent.com/4679072/145837910-15d8c6da-1dab-45d3-b833-cd6bc36312aa.png)

**Comment by manajay** [comment]
Any update ? I still have the problem . 
Maybe this can help u , maybe i mean 😁
https://github.com/FLEXTool/FLEX/blob/master/Classes/Network/PonyDebugger/FLEXNetworkObserver.m

**Comment by github-xiaogang** [comment]
Hi, woodpecker is open source now, will be appreciate if someone help fix some bugs :) , https://github.com/appwoodpecker/woodpecker-client
