### ISSUE TITLE
The new version is not working with physical devices but only with simulators.

### ISSUE THREAD

**Issue by ahmadmssm** [github-xiaogang/woodpeckeriOS#33]

**Comment by github-xiaogang** [comment]
Hi, thanks for your feedback!

Are you connect with usb? please try use wifi instead, some other developers also found couldn't work with usb connected.
I'll fixed this bug in a few days later, sorry for the bug.

**Comment by BayramInanc** [comment]
@github-xiaogang any news for usb connection?

**Comment by github-xiaogang** [comment]
@ahmadmssm @BayramInanc 
Hi, the latest 1.4.0 support USB connection now, you could download at AppStore.

**Comment by github-xiaogang** [comment]
BTW, woodpecker is now open source, you could find the latest update at here: https://github.com/appwoodpecker/woodpecker-client
