### ISSUE TITLE
链接正常，无法抓取网络请求

### ISSUE THREAD

**Issue by SanLiMikasa** [github-xiaogang/woodpeckeriOS#34]
xcode15， iOS 16.6 ， info.plist 已配置， usb连线调试，其他功能都正常。

**Comment by github-xiaogang** [comment]
网络工具目前通过hook方法实现，对wkwebview等请求支持不太好，建议使用专业抓包工具。

**Comment by SanLiMikasa** [comment]
> 网络工具目前通过hook方法实现，对wkwebview等请求支持不太好，建议使用专业抓包工具。
本地网络数据请求也不支持了吗

**Comment by github-xiaogang** [comment]
本地网络数据指的是非webview的吗？  工具是支持的。
从原理通过hook来实现网络监控是不可靠的：
1、各个app内部可能有自己的hook导致工具不可用
2、系统api变动需要及时跟进，维护成本很高
3、其他扩展功能（比如慢网模拟等）不能通过这种方式实现。

从长期角度目前的网络工具不会在深入维护，除非后面通过proxy的模式实现网络监控。

**Comment by SanLiMikasa** [comment]
ok，感谢回复
