### ISSUE TITLE
warning on simulator

### ISSUE THREAD

**Issue by wenshunb** [github-xiaogang/woodpeckeriOS#5]
hi, I get a warning when running my app on Xcode simulator: libMobileGestalt MobileGestalt.c:4130: Failed to get Computer Name, returning device name. How can I solve it? Thanks.

Xcode9.4.1+Swift 4+latest woodpecker on cocoapods

**Comment by github-xiaogang** [comment]
@Vancion I had tested with Xcode10.0 beta2 and without Woodpecker framework, got warning:
`libMobileGestalt MobileGestalt.c:879: MGIsDeviceOneOfType is not supported on this platform.`
So it seems like Xcode simulator's bug, and check this: 
https://stackoverflow.com/questions/50701321/xcode-error-on-simulation

**Comment by wenshunb** [comment]
sorry, I thought it is caused by woodpecker. will close the issue
