### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by fmirault** [github-xiaogang/woodpeckeriOS#6]
Hi !

I just bought Woodpecker on the mac app store, and I connected it with my application using Cocoapods.

Everything works fine... except I lost connection after 10 to 30 seconds, without any solution except re-launch my application.

Is there anything I am missing ?

Thank you

**Comment by github-xiaogang** [comment]
@fmirault I'm so sorry about this problem, could you provide more information, such as:
mac app version
Woodpecker iOS framework version
MacOS version
iOS version

Thank you!

**Comment by fmirault** [comment]
Hi !

This is my setup :
- mac app version : Version 1.1.3 (19)
- Woodpecker iOS framework version : 1.1.3
- MacOS version : Mojave (10.14)
- iOS version : 12

Thank you :)

**Comment by github-xiaogang** [comment]
Hi !  
Thanks for your reply! but I forget to ask your network setup, could you send it to me at woodpeckerapp@163.com. and feel free to email me at anytime in the future.
