### ISSUE TITLE
iOS9.3.3系统的真机找不到库

### ISSUE THREAD

**Issue by kobe1941** [github-xiaogang/woodpeckeriOS#7]
如题，使用CocoaPods集成，编译前已执行pod update，pod里可以找到framework：
![image](https://user-images.githubusercontent.com/7099017/48464791-b39d6d80-e81b-11e8-8ce3-1811916ef781.png)

但是APP启动后报错：
dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /private/var/containers/Bundle/Application/E4E57FB8-CBBC-4BD1-A461-D4CCEEBBC707/xxxxx.app/Frameworks/WoodPeckeriOS.framework/WoodPeckeriOS
  Reason: image not found

同样的操作iOS10.3.3的真机没问题。
你用了iOS10以上才支持的库？

**Comment by github-xiaogang** [comment]
@kobe1941 抱歉，一直没处理，是framework库问题，近期会进行更新
