### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by freedomct** [github-xiaogang/woodpeckeriOS#9]
大神 希望开个讨论组 或者群 这样 方便大家交流啊 
手动导入framework 在release环境下 会弹出与Mac端的连接界面嘛 ？

**Comment by github-xiaogang** [comment]
你好，目前Release会的，下个版本将不再自动弹连接界面。
讨论组目前还没什么必要，后面我建个slack讨论组吧，好了通知你。

**Comment by github-xiaogang** [comment]
1.1.8已经发布，不会再弹出连接界面啦。

**Comment by github-xiaogang** [comment]
@yun0628 你好，创建了slack群，需要的话请点击邀请链接：https://join.slack.com/t/woodpeckerapp/shared_invite/enQtNTkzNzU1OTAwMDgzLTM3MzdiZDdmZTI2M2EyNDhjYmViNmFmZThmNjM5ZjdmZDFlYjdlNTU5NWU1ZWVhZDU0ZmM5YjlmNjJlYjU1MjI
